<a href="https://colab.research.google.com/github/Sagaradhikari69/Word_Embedding-/blob/main/word_emb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install tensorflow

In [3]:
import tensorflow as tf
print (tf.__version__)

2.5.0



## ***Word Embedding Techniques using Embedding Layer in Keras***


In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size
voc_size=10000

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[3074, 7181, 2635, 2984], [3074, 7181, 2635, 7588], [3074, 8443, 2635, 2850], [6529, 6319, 6667, 6651, 3298], [6529, 6319, 6667, 6651, 9853], [6083, 3074, 7124, 2635, 987], [1940, 271, 9235, 6651]]


### Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3074 7181 2635 2984]
 [   0    0    0    0 3074 7181 2635 7588]
 [   0    0    0    0 3074 8443 2635 2850]
 [   0    0    0 6529 6319 6667 6651 3298]
 [   0    0    0 6529 6319 6667 6651 9853]
 [   0    0    0 6083 3074 7124 2635  987]
 [   0    0    0    0 1940  271 9235 6651]]


In [12]:
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
print(model.predict(embedded_docs))

[[[-2.2124385e-02  4.2207446e-02  2.6479747e-02  1.9291792e-02
   -3.9991725e-02  9.1109164e-03 -7.2978735e-03 -2.9052794e-02
   -3.0759776e-02  4.0141966e-02]
  [-2.2124385e-02  4.2207446e-02  2.6479747e-02  1.9291792e-02
   -3.9991725e-02  9.1109164e-03 -7.2978735e-03 -2.9052794e-02
   -3.0759776e-02  4.0141966e-02]
  [-2.2124385e-02  4.2207446e-02  2.6479747e-02  1.9291792e-02
   -3.9991725e-02  9.1109164e-03 -7.2978735e-03 -2.9052794e-02
   -3.0759776e-02  4.0141966e-02]
  [-2.2124385e-02  4.2207446e-02  2.6479747e-02  1.9291792e-02
   -3.9991725e-02  9.1109164e-03 -7.2978735e-03 -2.9052794e-02
   -3.0759776e-02  4.0141966e-02]
  [-3.7211619e-02 -1.2861550e-02  2.9930104e-02 -3.0446708e-02
    4.6413530e-02  6.8475716e-03  3.3115853e-02 -3.3634417e-03
    3.2264702e-03 -2.9641449e-02]
  [-1.4811896e-02  2.9202554e-02 -1.6647458e-02 -2.4140954e-02
    4.3156866e-02 -1.5297007e-02  2.9159036e-02  2.4654534e-02
    4.9606148e-02  2.7417507e-02]
  [-3.4299813e-02  4.8785914e-02  4.9072

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 3074, 7181, 2635, 2984], dtype=int32)

In [18]:
print(model.predict(embedded_docs)[0])


[[-0.02212439  0.04220745  0.02647975  0.01929179 -0.03999173  0.00911092
  -0.00729787 -0.02905279 -0.03075978  0.04014197]
 [-0.02212439  0.04220745  0.02647975  0.01929179 -0.03999173  0.00911092
  -0.00729787 -0.02905279 -0.03075978  0.04014197]
 [-0.02212439  0.04220745  0.02647975  0.01929179 -0.03999173  0.00911092
  -0.00729787 -0.02905279 -0.03075978  0.04014197]
 [-0.02212439  0.04220745  0.02647975  0.01929179 -0.03999173  0.00911092
  -0.00729787 -0.02905279 -0.03075978  0.04014197]
 [-0.03721162 -0.01286155  0.0299301  -0.03044671  0.04641353  0.00684757
   0.03311585 -0.00336344  0.00322647 -0.02964145]
 [-0.0148119   0.02920255 -0.01664746 -0.02414095  0.04315687 -0.01529701
   0.02915904  0.02465453  0.04960615  0.02741751]
 [-0.03429981  0.04878591  0.04907269  0.0488638  -0.04264233 -0.0042323
   0.00837729  0.04184207  0.01668018 -0.00139151]
 [ 0.0106496  -0.04562009 -0.00667486  0.04019758  0.03276518 -0.03056874
  -0.0385064   0.03025753  0.02594397  0.00226688]]
